### ISSUE TITLE
请问下你的论文链接可以分享下吗？arxiv上找不到

### ISSUE THREAD

**Issue by nlpofwhat** [lyy1994/reformer#1]

**Comment by lyy1994** [comment]
你好，论文正在上传到arXiv上，审核结束之后我会第一时间告诉你。谢谢！

**Comment by nlpofwhat** [comment]
膜拜大佬！谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lee"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 中午11:42
收件人: "lyy1994/reformer"<reformer@noreply.github.com&gt;; 
抄送: "@My heart will go on."<952167295@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lyy1994/reformer] 请问下你的论文链接可以分享下吗？arxiv上找不到 (#1)




你好，论文正在上传到arXiv上，审核结束之后我会第一时间告诉你。谢谢！

**Comment by zhengcaiyunjob** [comment]
@lyy1994 论文呢？

**Comment by lyy1994** [comment]
论文已经放到arXiv上了：[https://arxiv.org/abs/2002.06546](url)

**Comment by nlpofwhat** [comment]
非常感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lee"<notifications@github.com&gt;; 
发送时间: 2020年2月19日(星期三) 上午10:23
收件人: "lyy1994/reformer"<reformer@noreply.github.com&gt;; 
抄送: "@My heart will go on."<952167295@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lyy1994/reformer] 请问下你的论文链接可以分享下吗？arxiv上找不到 (#1)




论文已经放到arXiv上了：https://arxiv.org/abs/2002.06546
